config/routes.rb
Rails.application.routes.draw do
  resources :photos, only: :rate do
    member do
      patch :rate
    end
  end

  resources :albums do
    member do
      post :unlock
    end
  end

  resources :domains

  namespace :manage do
    resources :albums
    resources :domains
    resources :photos, except: [:new, :edit, :show, :index]
  end

  match 'public/:domain_name/:id/:suffix(.:format)' => 'manage/albums#view', :domain_name => /[A-Za-z0-9\.]+?/, :via => [:get], :as => 'domain_album'

  devise_for :user, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins
  
  mount RailsAdmin::Engine => '/backend', as: 'rails_admin'

  root 'albums#home'
end

app/models/domain.rb
class Domain
  require "resolv"
  DNS_PREFIX = "imagepol"

  include Mongoid::Document
  include Mongoid::Timestamps::Created

  belongs_to :user
  has_many :albums, dependent: :destroy

  index({ name: 1 }, { unique: true, name: "name_index" })

  field :name, type: String
  attr_accessor :verified

  def verify!
    verify_domain unless self.verified == true
  end

  validates_format_of :name, with: /\A[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}?\Z/ix

  protected
  def verify_domain

    Resolv::DNS.open do |domain|
      @dns = domain.getresources("#{DNS_PREFIX}.#{name}", Resolv::DNS::Resource::IN::TXT)
      self.verified = !@dns.empty? && @dns.first.strings.first == self.user_id.to_s
    end
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show]
  # skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all.page(params[:page])

    render 'manage/domains/index'
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    @albums = @domain.albums.page(params[:page])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_actions.html.erb
<%= link_to domain_album_path(
    domain_name: (album.domain_id.nil? ? album.id : @domain.name),
    id: album.slug,
    suffix: album.suffix.parameterize
  ), style: "margin-left: 5px", class: "btn-floating right btn-small waves-effect waves-light orange" do %>
  <i class="material-icons">play_arrow</i>
<% end %>

<% if user_signed_in? and current_user.id == album.user_id %>
  <%= link_to edit_manage_album_path(album), style: "margin-left: 5px", 
    class: "btn-floating right btn-small waves-effect waves-light #{@color}" do %>
    <i class="material-icons">edit</i>
  <% end %>
  <%= link_to manage_album_path(album), 
    method: :delete,
    data: { confirm: 'Are you sure?' },
    class: "btn-floating right btn-small waves-effect waves-light red" do %>
    <i class="material-icons">delete</i>
  <% end %>
<% end %>

app/views/domains/show.html.erb
<div class="row page-title">
  <h4><%= t("domains.albums.title", name: @domain.name) %></h4>
</div>

<div class="row">
  <div class="col s12 m3">
    <%= undraw("like_dislike", color: "#{@color}", size: "100%") %>
  </div>
  <div class="col s12 m9">

    <table class="highlight">
      <thead>
      <tr>
        <th width="20">#</th>
        <th><%= t("albums.columns.name") %></th>
        <th></th>
        <th width="20"></th>
      </tr>
      </thead>

      <tbody>
      <% @albums.each do |album| %>
        <tr>
          <td></td>
          <td>
            <%= link_to album.name + ' / ' + album.suffix, domain_album_path(
                domain_name: (album.domain_id.nil? ? album.id : @domain.name),
                id: album.slug,
                suffix: album.suffix.parameterize) %>
          </td>
          <td class="right" style="width: 120px">
            <%= render 'actions', domain: @domain, album: album %>
          </td>
          <td></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <%= paginate @albums %>
  </div>
</div>