config/routes.rb
Rails.application.routes.draw do
  resources :photos, only: :rate do
    member do
      patch :rate
    end
  end

  resources :albums do
    member do
      post :unlock
    end
  end

  resources :domains

  namespace :manage do
    resources :albums
    resources :domains
    resources :photos, except: [:new, :edit, :show, :index]
  end

  match 'public/:domain_name/:id/:suffix(.:format)' => 'manage/albums#view', :domain_name => /[A-Za-z0-9\.]+?/, :via => [:get], :as => 'domain_album'

  devise_for :user, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins
  
  mount RailsAdmin::Engine => '/backend', as: 'rails_admin'

  root 'albums#home'
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :set_locale, :redirect_users_without_subdomain, :load_color

  layout :set_layout

  # @TODO not sure if this is 100% useful
  def redirect_users_without_subdomain
    if user_signed_in? and !request.subdomain.blank? and params[:controller] != "devise/sessions"
      redirect_to url_for(subdomain: false) and return
    end
  end

  def load_color
    @color = I18n.t("theme.color", :default => 'teal')
  end
  
  def set_locale
    I18n.locale = current_user.try(:locale) || 
      extract_locale_from_subdomain || 
      extract_locale_from_accept_language_header || 
      I18n.default_locale
  end

  def set_layout
    if user_signed_in?
      "application"
    else
      devise_controller? ? "login" : "application"
    end
  end

  private
    def extract_locale_from_subdomain
      parsed_locale = request.subdomains.first
      I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
    end

    def extract_locale_from_accept_language_header
      accept_language = request.env['HTTP_ACCEPT_LANGUAGE']
      return unless accept_language
  
      locale = accept_language.scan(/^[a-z]{2}/).first

      I18n.available_locales.map(&:to_s).include?(locale) ? locale : nil
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  PHOTOS_PER_PAGE = 24
end

app/views/application/_language_switcher.html.erb
<div id="tx-live-lang-container" class="txlive-langselector txlive-langselector-bottomright">
  <ul id="tx-live-lang-picker" class="txlive-langselector-list notranslate">
    <% I18n.available_locales.each do |locale| %>
      <li onclick="location.href='http://<%= locale != :en ? "#{locale}." : "" %><%= Rails.application.config.base_url %>';">
        <%= I18n.t("i18n.language.name", locale: locale) %>
      </li>
    <% end %>
  </ul>
  <div class="txlive-langselector-toggle notranslate" id="tx-live-lang-toggle">
      <span class="txlive-langselector-current" id="tx-live-lang-current">
        <%= I18n.t("i18n.language.name", locale: I18n.locale) %>
      </span>
    <span class="txlive-langselector-marker"></span>
  </div>
</div>
<script type="application/javascript">
    jQuery( "#tx-live-lang-container" ).click(function() {
        jQuery( "#tx-live-lang-picker" ).toggle( "slow");
    });
</script>

app/views/application/_menu.html.erb
<header>
  <div class="navbar-fixed">
    <nav class="white" role="navigation">
      <div class="nav-wrapper container">
        <%= link_to root_path, html_options = {class: "brand-logo", id: "logo-container"} do %>
          <span class="left">
            <img src="<%= asset_path('logo.svg') %>">
          </span>
          <b class="<%= @color %>-text">image</b><b>pol</b> <sup style="font-size: 0.5em;" class="red-text">beta</sup>
        <% end %>
        <ul class="right hide-on-med-and-down">
          <% unless user_signed_in? %>
            <li><%= link_to(t('devise.sessions.new.sign_in'), new_user_session_path)  %></li>
            <li><%= link_to(t('devise.registrations.new.sign_up'), new_user_registration_path)  %></li>
          <% else %>
            <li><%= link_to t('domains.title'), domains_path %></li>
            <li><%= link_to t('albums.title'), albums_path %></li>
          <% end %>

          <!-- Dropdown Trigger -->
          <% if user_signed_in? %>
            <li>
              <a class="dropdown-trigger" data-alignment="left" href="#!" data-target="dropdown1">
                <%= raw(t("message.logged_in_as", name: current_user.email)) %>
                <i class="material-icons right">menu</i>
              </a>
            </li>
          <% end %>
        </ul>
        <a id="sidenav" href="#" data-turbolinks="false" data-target="slide-out" class="button-collapse sidenav-trigger"><i class="material-icons">menu</i></a>
      </div>
    </nav>
  </div>

  <%= render "menu_dropdown", id: 'dropdown1' %>

  <ul id="slide-out" class="sidenav">

    <li>
      <div class="user-view">
        <div class="background <%= @color %>"></div>
          <% if user_signed_in? %>
            <% if current_user.image.blank? %>
              <i class="material-icons white-text medium">account_circle</i>
            <% else %>
              <img class="circle" src="<%= current_user.image %>">
            <% end %>
            <span class="white-text name"><%= current_user.name %></span>
            <span class="white-text email"><%= current_user.email %></span>
          <% else %>
            <i class="material-icons white-text medium">account_circle</i>
            <span class="white-text name">Welcome,</span>
            <span class="white-text email">guest!</span>
          <% end %>
      </div>
    </li>

    <% unless user_signed_in? %>
      <li><%= link_to(t('devise.sessions.new.sign_in'), new_user_session_path)  %></li>
      <li><%= link_to(t('devise.registrations.new.sign_up'), new_user_registration_path)  %></li>
    <% else %>
      <li><%= link_to t('domains.title'), domains_path %></li>
      <li><%= link_to t('albums.title'), albums_path %></li>
    <% end %>

    <% if user_signed_in? %>
      <li class="divider"></li>
      <li><%= link_to t('domains.new'), new_manage_domain_path %></li>
      <li><%= link_to t('domains.my'), manage_domains_path %></li>

      <li class="divider"></li>
      <li><%= link_to t('albums.new'), new_manage_album_path %></li>
      <li><%= link_to t('albums.my'), manage_albums_path %></li>

      <li class="divider"></li>
      <li><%= link_to t('devise.registrations.edit.title', resource: User.model_name.human), edit_user_registration_path, :class => 'navbar-link' %></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
    <% end %>
  </ul>

</header>

app/views/application/_menu_dropdown.html.erb
<!-- Dropdown Structure -->
<ul id="<%= id %>" class="dropdown-content">
  <% if user_signed_in? %>
    <li><%= link_to t('domains.new'), new_manage_domain_path %></li>
    <li><%= link_to t('domains.my'), manage_domains_path %></li>

    <li class="divider"></li>
    <li><%= link_to t('albums.new'), new_manage_album_path %></li>
    <li><%= link_to t('albums.my'), manage_albums_path %></li>

    <li class="divider"></li>
    <li><%= link_to t('devise.registrations.edit.title', resource: User.model_name.human), edit_user_registration_path, :class => 'navbar-link' %></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
  <% end %>
</ul>

app/views/application/_photo_card.html.erb
<div class="col s12 m6 l4">
  <div class="card sticky-action" style="overflow: visible;">
    <div class="card-image">
        <%= image_tag(photo.upload(:standard), 
          # 'data-caption': "A picture", 
          width: "350",
          class: "materialboxed") %>
    </div>

    <div class="card-action">
      <div class="row" style="margin-bottom: 0;">
        <div class="right">
          <%= t('photos.votes', count: photo.rate_count) %>
          <% unless user_signed_in? %>
            <%= t('albums.login_to_vote') %>
          <% end %>
        </div>

        <div class="left">
          <% if user_signed_in? %>
            <%= form_with(model: photo, url: rate_photo_path(photo), local: true) do |form| %>
              <%= form.hidden_field :vote, value: !(photo.rated_by? current_user) %>
              <% if photo.rated_by? current_user %>
                <%= link_to "#", title: t('albums.voted'), :onclick => "$(this).closest('form').submit()" do %>
                  <i class="material-icons red-text left">favorite</i><%= t('albums.voted') %>
                <% end %>
              <% else %>
                <%= link_to "#", title: t('albums.vote'), :onclick => "$(this).closest('form').submit()" do %>
                  <i class="material-icons left">favorite_border</i><%= t('albums.vote') %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_photo_card_upload_tpl.html.erb
<div class="col s12 m6 l4">
  <div class="card sticky-action" style="overflow: visible;">
    <div class="card-image waves-effect waves-block waves-light">
      <img width="350" data-dz-thumbnail />
    </div>

    <div class="card-action">
    </div>
  </div>
</div>